### ISSUE TITLE
can-patch should account for object types

### ISSUE THREAD

**Issue by JaneOri** [feathers-plus/feathers-mocha-utils#1]
```js
const assert = require('assert')

module.exports = function (service, recordToPatch, attributeToPatch, newValue, done) {
  return service.patch(recordToPatch._id.toString(), { [attributeToPatch]: newValue })
    .then(response => {
      assert.deepEqual(response[attributeToPatch], newValue, `can patch ${attributeToPatch} attribute`)
      done()
    })
    .catch(done)
}
```

**Comment by Mattchewone** [comment]
Need to also account for `password` field somehow, as this is hard to verify.

**Comment by JaneOri** [comment]
Aside from the hashing that should happen to 'newValue' of a password, password hashes might not return from the same service you can patch with either.
They're probably best tested with something specific/custom rather than this simple util because of all the edge cases

**Comment by Mattchewone** [comment]
I totally agree @James0x57 I guess we should make it clear in the README, that Passwords or any other fields that are removed from the response should be tested separately.

**Comment by JaneOri** [comment]
`If your passwords can be tested with this util, you're doing it wrong.` 😜
